title: all About Me
author: hxwang
email: hxwang@ebnet.org
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This site will have my name, a picture, a brag sheet, and my contact information.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  hxwanghxwang # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
